## other configuration excluded from example...
exclude_patterns:
- "coverage/"
- "node_modules/**"
- ".next/**"
- ".circleci/**"
- "src/__tests__/**"
- "src/Constants/**"
- "src/Config/**"
- "**/reducer.ts"
- "**/actions.ts"